### ISSUE TITLE
Message if there are no updates

### ISSUE THREAD

**Issue by linuxlite** [linuxlite/liteupdatesnotify#6]
If there are no updates, then the notify-send message reports, 'There are no updates available" or similar message.

**Comment by ralphys** [comment]
Well, instead of nagging the user with "There are no updates available", wouldn't it be better not to nag the user at all?

if $updates_available then nag... else dont_nag

**Comment by linuxlite** [comment]
That's a good point, but then the user may assume their notifier isn't working properly, as they have no idea whether there are updates available or not.

**Comment by linuxlite** [comment]
Perhaps a better solution would be make this message appear only once.
