### ISSUE TITLE
Nofified there was 1 update, had 10

### ISSUE THREAD

**Issue by linuxlite** [linuxlite/liteupdatesnotify#7]
Got a notification there was one update, ran Install Updates 30 seconds later, was told there was 10.

![screenshot_2016-12-14_12-02-18](https://cloud.githubusercontent.com/assets/5382578/21162994/34d06adc-c1f5-11e6-8fd4-d0190ee35a8e.png)

**Comment by ralphys** [comment]
That seems actually fine. I had 10 updates available for installation (I'm checking every 30 minutes for testing purposes)... and 11 more updates showed up later. It seems that new updates became available after running updatenotify and before running Install Updates on your end. Perhaps (for testing purposes) you want to change updatenotify to check for updates more often.

Here is what I'm seeing in my notification (note that I previously had just 10 updates)

![1](https://cloud.githubusercontent.com/assets/15816320/21164486/3c195242-c167-11e6-96f2-32ebb9f67d7a.png)

**Comment by linuxlite** [comment]
Possible solution, what do you think? Add a postinst file to the deb package that:

- checks who is in the sudo group
- adds those users to sudoers file eg.

`jerry ALL=NOPASSWD: /usr/local/sbin/updatenotify`

- change /usr/local/sbin/updatenotify line 5 from:

`apt-get update > /dev/null 2>&1`

to

`sudo apt-get update > /dev/null 2>&1`

**Comment by linuxlite** [comment]
Have this so far and it works a treat. Uploaded a new Tor package to our repo, and it was discovered straight away with the above modified updatenotify.

```
#! /bin/sh
# Postinst script for Lite Update Notify

set -e

IDUSER=$(grep -Po '^sudo.+:\K.*$' /etc/group)

if [ `id -u $IDUSER 2>/dev/null || echo -1` -ge 0 ]; then 
    echo "$IDUSER ALL=NOPASSWD: /usr/local/sbin/updatenotify" >> /etc/sudoers

else
	echo "Script failed..."
fi
```

But would like to modify the above script to add ALL users with sudo access to the sudoers file.

**Comment by ralphys** [comment]
I'm failing to see what we are trying to fix. I installed one of the updates manually, let the script check for updates again on its cycle and it gave me the correct amount of updates left:

![2](https://cloud.githubusercontent.com/assets/15816320/21167264/56b8411e-c179-11e6-92f3-174f970f69dd.png)

I'm obviously missing something you are seeing.

**Comment by linuxlite** [comment]
We're getting the results of:

`/usr/lib/update-notifier/apt-check --human-readable`

from the updatenotify script, but I'm thinking that:

`apt-get update > /dev/null 2>&1`

needs sudo in order for it to get updates properly.

**Comment by linuxlite** [comment]
Am I over-thinking this?

**Comment by ralphys** [comment]
Let's talk about this in Dev Corner
